import { auth, db, CONFIG } from './firebase.js';
import { onAuthStateChanged, signOut, updatePassword, updateEmail, EmailAuthProvider, reauthenticateWithCredential } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { collection, getDocs, addDoc, doc, updateDoc, deleteDoc, serverTimestamp, getDoc, query, orderBy, setDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const logoutBtn = document.getElementById('logout-btn');
const adminEmailSpan = document.getElementById('admin-email');
const saveAccountBtn = document.getElementById('save-account-btn');
const productsList = document.getElementById('products-list');
const addProductBtn = document.getElementById('add-product-btn');
const productModal = document.getElementById('product-modal');
const closeBtn = document.querySelector('.close-btn');
const productForm = document.getElementById('product-form');
const modalTitle = document.getElementById('modal-title');
const saveProductBtn = document.getElementById('save-product-btn');
const imagePreview = document.getElementById('image-preview');
const fileInput = document.getElementById('product-image-file');
const logoPreview = document.getElementById('logo-preview');
const logoFileInput = document.getElementById('logo-file');
const logoUrlInput = document.getElementById('logo-url');
const usernameInput = document.getElementById('username-input');
const bioInput = document.getElementById('bio-input');
const waInput = document.getElementById('wa-input');
const shopeeInput = document.getElementById('shopee-input');
const saveSettingsBtn = document.getElementById('save-settings-btn');

document.addEventListener('DOMContentLoaded', () => { lucide.createIcons(); setupTabs(); startClock(); });

function startClock() { const u=()=>{const n=new Date();const t=n.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'});const d=n.toLocaleDateString('id-ID',{weekday:'long',year:'numeric',month:'long',day:'numeric'});document.getElementById('live-clock').textContent=t;document.getElementById('live-date').textContent=d;document.getElementById('big-clock').textContent=t;document.getElementById('big-date').textContent=d;};u();setInterval(u,1000); }
async function loadStats() { const q=query(collection(db,"products"));const s=await getDocs(q);let t=0,e=0;s.forEach(d=>{t++;if(d.data().stok==0)e++;});document.getElementById('stat-total').textContent=t;document.getElementById('stat-empty').textContent=e; }

function showToast(m,e=false) { const t=document.getElementById('toast'),b=document.getElementById('toast-box'); b.className=`earth-card p-4 text-sm font-semibold text-center flex items-center justify-center gap-2 ${e?'border border-red-100 text-red-600':'border border-green-100 text-green-600'}`; b.innerHTML=`<i data-lucide="${e?'alert-circle':'check-circle'}" class="w-4 h-4"></i><span>${m}</span>`; lucide.createIcons(); t.classList.remove('-translate-y-10','opacity-0','pointer-events-none');t.classList.add('translate-y-0','opacity-100');setTimeout(()=>{t.classList.add('-translate-y-10','opacity-0','pointer-events-none');t.classList.remove('translate-y-0','opacity-100');},3000); }

onAuthStateChanged(auth,(user)=>{if(user){adminEmailSpan.textContent=user.email;document.getElementById('new-email-input').value=user.email;loadProducts();loadSettings();loadStats();}else window.location.href='login.html';});
logoutBtn.addEventListener('click',()=>signOut(auth));
function setupTabs(){document.querySelectorAll('.tab-btn').forEach(b=>{b.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(x=>{x.classList.remove('sidebar-active','text-white');x.classList.add('text-gray-400');});document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));b.classList.add('sidebar-active','text-white');b.classList.remove('text-gray-400');document.getElementById(`page-${b.dataset.page}`).classList.add('active');if(b.dataset.page==='dashboard')loadStats();};});}

saveAccountBtn.addEventListener('click',async()=>{const ne=document.getElementById('new-email-input').value,np=document.getElementById('new-password-input').value,cp=document.getElementById('reauth-password-input').value;if(!cp)return showToast('Wajib masukkan password lama!',true);if(ne===auth.currentUser.email&&!np)return showToast('Tidak ada perubahan.',true);saveAccountBtn.disabled=true;saveAccountBtn.innerHTML='...';try{const u=auth.currentUser;await reauthenticateWithCredential(u,EmailAuthProvider.credential(u.email,cp));if(ne!==u.email){if(!ne.includes('@'))throw new Error('Format email salah!');await updateEmail(u,ne);}if(np){if(np.length<6)throw new Error('Password min 6!');await updatePassword(u,np);}showToast('Akun diperbarui! Keluar otomatis...');setTimeout(()=>signOut(auth),1500);}catch(e){let m=e.message;if(e.code==='auth/wrong-password')m='Password lama SALAH!';showToast(m,true);}finally{saveAccountBtn.disabled=false;saveAccountBtn.innerHTML='<i data-lucide="key" class="w-4 h-4"></i> Update Akun';lucide.createIcons();}});

async function loadProducts(){productsList.innerHTML='<div class="skeleton h-24 rounded-2xl"></div>';const q=query(collection(db,"products"),orderBy("createdAt","desc"));const s=await getDocs(q);productsList.innerHTML='';if(s.empty){productsList.innerHTML='<div class="text-center py-16"><i data-lucide="package-open" class="lucide w-16 h-16 mx-auto text-gray-200 mb-4"></i><p class="text-gray-300 text-sm">Belum ada produk</p></div>';lucide.createIcons();return;}s.forEach(d=>{const p=d.data();const c=document.createElement('div');c.className="earth-card p-3 flex items-center gap-3";c.innerHTML=`<img src="${p.img}" class="w-14 h-14 object-cover rounded-lg flex-shrink-0"><div class="flex-1 min-w-0"><h3 class="font-semibold text-sm truncate text-gray-900">${p.nama}</h3><p class="text-gray-900 font-bold text-sm">Rp${p.harga.toLocaleString('id-ID')}</p><p class="text-[10px] text-gray-400">Stok: ${p.stok}</p></div><div class="flex flex-col gap-1"><button class="edit-btn bg-gray-100 text-gray-600 px-2 py-1 rounded-lg text-[10px]" data-id="${d.id}">Edit</button><button class="delete-btn bg-gray-100 text-gray-600 px-2 py-1 rounded-lg text-[10px]" data-id="${d.id}">Hapus</button></div>`;productsList.appendChild(c);});}
addProductBtn.addEventListener('click',()=>{productForm.reset();document.getElementById('product-id').value='';document.getElementById('product-image-url').value='';imagePreview.style.display='none';fileInput.value='';modalTitle.textContent='Tambah Produk';productModal.style.display='flex';});
const closeModal=()=>productModal.style.display='none';closeBtn.addEventListener('click',closeModal);window.addEventListener('click',e=>{if(e.target==productModal)closeModal();});
fileInput.addEventListener('change',()=>{const f=fileInput.files[0];if(f){if(imagePreview.src.startsWith('blob:'))URL.revokeObjectURL(imagePreview.src);imagePreview.src=URL.createObjectURL(f);imagePreview.style.display='block';}});
productsList.addEventListener('click',async e=>{const id=e.target.dataset.id;if(e.target.classList.contains('edit-btn')){const ds=await getDoc(doc(db,"products",id));const p=ds.data();document.getElementById('product-id').value=id;document.getElementById('product-name').value=p.nama;document.getElementById('product-price').value=p.harga;document.getElementById('product-stock').value=p.stok;document.getElementById('product-description').value=p.deskripsi||'';document.getElementById('product-wa').value=p.wa||'';document.getElementById('product-shopee').value=p.shopee||'';document.getElementById('product-image-url').value=p.img;imagePreview.src=p.img;imagePreview.style.display='block';fileInput.value='';modalTitle.textContent='Edit Produk';productModal.style.display='flex';}if(e.target.classList.contains('delete-btn')){if(confirm('Hapus produk ini?')){await deleteDoc(doc(db,"products",id));loadProducts();showToast('Dihapus!');}}});
productForm.addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('product-id').value,f=fileInput.files[0];let img=document.getElementById('product-image-url').value;if(f){saveProductBtn.disabled=true;saveProductBtn.innerHTML='...';img=await uploadToCloudinary(f);if(!img){saveProductBtn.disabled=false;saveProductBtn.innerHTML='Simpan';return;}}if(!img)return showToast('Gambar wajib!',true);const d={nama:document.getElementById('product-name').value,harga:Number(document.getElementById('product-price').value),stok:Number(document.getElementById('product-stock').value),deskripsi:document.getElementById('product-description').value,wa:document.getElementById('product-wa').value,shopee:document.getElementById('product-shopee').value,img,updatedAt:serverTimestamp()};saveProductBtn.disabled=true;saveProductBtn.innerHTML='...';try{if(id){await updateDoc(doc(db,"products",id),d);showToast('Diperbarui!');}else{d.createdAt=serverTimestamp();await addDoc(collection(db,"products"),d);showToast('Ditambahkan!');}closeModal();loadProducts();loadStats();}catch(e){showToast(e.message,true);}finally{saveProductBtn.disabled=false;saveProductBtn.innerHTML='Simpan';}});
async function loadSettings(){const s=await getDoc(doc(db,"settings","toko"));if(s.exists()){const d=s.data();usernameInput.value=d.username||'';bioInput.value=d.bio||'';waInput.value=d.wa||'';shopeeInput.value=d.shopee||'';logoUrlInput.value=d.logo||'';logoPreview.src=d.logo||'https://placehold.co/200x200/F4F4F4/AAAAAA?text=Logo';}}
logoFileInput.addEventListener('change',()=>{const f=logoFileInput.files[0];if(f){if(logoPreview.src.startsWith('blob:'))URL.revokeObjectURL(logoPreview.src);logoPreview.src=URL.createObjectURL(f);}});
saveSettingsBtn.addEventListener('click',async()=>{saveSettingsBtn.disabled=true;saveSettingsBtn.innerHTML='...';let l=logoUrlInput.value,f=logoFileInput.files[0];if(f){l=await uploadToCloudinary(f);if(!l){saveSettingsBtn.disabled=false;saveSettingsBtn.innerHTML='Simpan';return;}}try{await setDoc(doc(db,"settings","toko"),{username:usernameInput.value,bio:bioInput.value,wa:waInput.value,shopee:shopeeInput.value,logo:l});showToast('Tersimpan!');}catch(e){showToast(e.message,true);}finally{saveSettingsBtn.disabled=false;saveSettingsBtn.innerHTML='Simpan';}});
async function uploadToCloudinary(f){const fd=new FormData();fd.append('file',f);fd.append('upload_preset',CONFIG.cloudinary.uploadPreset);try{const r=await fetch(`https://api.cloudinary.com/v1_1/${CONFIG.cloudinary.cloudName}/image/upload`,{method:'POST',body:fd});const d=await r.json();if(d.secure_url)return d.secure_url;throw new Error('Gagal');}catch(e){showToast(e.message,true);return null;}}
